// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Direcci¢n: Amsterdam 312 col. Hipodromo Condesa
// Tel‚fono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisi¢n  1.1-A
/*

char *f_f_hoy(void);
  // Regresa la fecha actual del sistema con formato cadena como un puntero
  // Nombre del archivo: F_F_HOY.CPP



#include "fechas.hpp"

char *f_f_hoy(void)
{
    char xf[15];
    unsigned int dia = 0, mes = 0, ano = 0;
    f_f_hoy(dia,mes,ano);
    f_greg__fecha(dia,mes,ano,xf);
    return xf;
}
*/
