// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Direcci¢n: Amsterdam 312 col. Hipodromo Condesa
// Tel‚fono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisi¢n  1.0.0


// Definicion de los colores dentro del sistema



#define Negro     0
#define Gris1     56 //8
#define Gris9     7
#define Azul1     1
#define Azul9     57 //9
#define Verde1    2
#define Verde9    58 //10
#define Cian1     3
#define Cian9     59 //11
#define Rojo1     4
#define Rojo9     60 //12
#define Magenta1  5
#define Magenta9  61 //13
#define Cafe      20  
#define Amarillo  62 //14
#define Blanco    63 //15

