const char color[] = {Negro,Gris1,Gris9,Azul1,Azul9,Verde1,Verde9,Cian1,Cian9,Rojo1,Rojo9,Magenta1,Magenta9,Cafe,Amarillo,Blanco};
const char cn1[]   = {0    ,180  ,174  ,0    ,0    ,0     ,0     ,0    ,0    ,255  ,164  ,255     ,0       ,128 ,255     ,255};
const char cn2[]   = {0    ,180  ,174  ,178  ,192  ,180   ,90    ,180  ,164  ,0    ,0    ,0       ,0       ,64  ,255     ,255};
const char cn3[]   = {0    ,180  ,174  ,187  ,160  ,168   ,0     ,180  ,164  ,0    ,0    ,255     ,128     ,64  ,0       ,255};
