// Autor:     Antonio Carrillo Ledesma
// Direcci¢n: Amsterdam 312, colonia Hip¢dromo Condesa
// Tel‚fono:  574-43-53
// Propiedad intelectual, derechos reservados conforme a la ley (Registro en tr mite)
// 1993 -1994


#ifndef __R_M_C_HPP__
#define __R_M_C_HPP__

   const unsigned int max_len = 500;            // Longitud del arreglo de trabajo (Utilizable en las rutinas de manipulaci¢n de cadena), si se modifica devera recompilar R_M_C
   #define            Cadena_maxima_seg  510    // Longitud de la maxima cadena para solicitar memoria
   #define            Cadena_maxima      500    // Longitud de la maxima cadena

#endif
