//////////////////////////////////////////////////////////////
//                                                          //
//              I N T E G R A    V E R. 1.0                 //
//       (Analisador de sistemas din micos interativos)     //
//                                                          //
// Desarrollado para ambiente DOS en modo de video          //
// VGA y SVGA a 256 colores.                                //
//                                                          //
// Autores:                                                 //
//                                                          //
//     Humberto Carrillo Calvet                             //
//     Antonio Carrillo Ledesma                             //
//     Luis A. Nava Fernandez                               //
//                                                          //
// Desarrollado en:                                         //
//                                                          //
//     Laboratorio de Din mica no Lineal                    //
//     Facultad de Ciencias, UNAM, M‚xico D.F.              //
//     Tel‚fono 6 22-48-70                                  //
//     E-mail: dinamica@athena.fciencias.unam.mx            //
//                                                          //
// Propiedad intelectual, todos los derechos reservados     //
// conforme a la ley, registro en tr mite.                  //
// Revisi¢n  1.1-A                                          //
//                                                          //
//////////////////////////////////////////////////////////////


#ifdef _IDIOMA_ESPANOL_
   #define VERSION       "Versi¢n DOS/C++ 1.05C (20-D) á"
   #define REGISTRO      "REGISTRO No. 167025 DERECHO DE AUTOR, SEP 1994-2000"
   #define VER_INTERFAZ  "INTERFAZ DEL SISTEMA INTEGRA DOS/C++ 1.05D"
   #define VER_INTEGRA   "INTEGRA DOS/C++ 1.05C"
   #define VER_CTRL_GRF  "CONTROL DE GRAFICOS DEL SISTEMA INTEGRA DOS/C++ 1.05A"
   #define FECHA_VERSION "29 de Abril del 2000"
#else
   #define VERSION       "Versi¢n DOS/C++ 1.05C (20-D) á"
   #define REGISTRO      "REGISTRO No. 167025 DERECHO DE AUTOR, SEP 1994-2000"
   #define VER_INTERFAZ  "INTERFAZ DEL SISTEMA INTEGRA DOS/C++ 1.05D"
   #define VER_INTEGRA   "INTEGRA DOS/C++ 1.05C"
   #define VER_CTRL_GRF  "CONTROL DE GRAFICOS DEL SISTEMA INTEGRA DOS/C++ 1.05A"
   #define FECHA_VERSION "29 de Abril del 2000"
#endif

