// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Direcci¢n: Amsterdam 312 col. Hipodromo Condesa
// Tel‚fono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisi¢n  1.1-A

/*
extern "C" {
   #include <string.h>
}

void encripta_cadena(const char *cad, char *cad_encp);
  // Encripta la cadena CAD retornando una cadena encriptada


void encripta_cadena(const char *cad, char *cad_encp)
{
   strcpy(cad_encp,cad);
   // Invierte la cadena
   strrev(cad_encp);
}
*/


