// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Direcci¢n: Amsterdam 312 col. Hipodromo Condesa
// Tel‚fono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisi¢n  1.1-A

////////////////////////
// No se a revisado
////////////////////////


void s_borra_palabra_sig(char *cad, const unsigned int pos);
  // Borra la palabra siguiente que se encuentre despues de la posicion POS
  // Nombre del archivo:S_BORRPL.CPP



void s_borra_palabra_sig(char *cad, const unsigned int pos)
{



}

