// Autor:     Antonio Carrillo Ledesma.
// R.F.C.:    CALA-691229-TV5
// Direcci¢n: Amsterdam 312 col. Hipodromo Condesa
// Tel‚fono:  5-74-43-53

// Propiedad intelectual, todos los derechos reservados conforme a la ley, registro en tr mite
// Revisi¢n  1.1-A




int s_pos_sig_car_dist(const char *cad);
  // Retorna la posicion del siguiente caracter distinto de CAR en la cadena CAD
  // retorna -1 si no es encontrado


int s_pos_sig_car_dist(const char *cad,const char car)
{
   int i = -1;
//   for(*cad) {
//      if(*cad != car) return i;
//   }
   return i;
}

